// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVWZykSDzxOraakKBS91_Qo0md2QB1quU',
    appId: '1:606904438190:web:6b5514d46fefb60c138c3f',
    messagingSenderId: '606904438190',
    projectId: 'attendplus-b771d',
    authDomain: 'attendplus-b771d.firebaseapp.com',
    storageBucket: 'attendplus-b771d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByRVeKM7RrLxkXQbheDoqhPkZK6CuTxZY',
    appId: '1:606904438190:android:1cd81c4c6f0020fc138c3f',
    messagingSenderId: '606904438190',
    projectId: 'attendplus-b771d',
    storageBucket: 'attendplus-b771d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO-izy5yqaBgGtDy79_g6pJLZyIBVWUpI',
    appId: '1:606904438190:ios:7867790ca253ac2a138c3f',
    messagingSenderId: '606904438190',
    projectId: 'attendplus-b771d',
    storageBucket: 'attendplus-b771d.firebasestorage.app',
    iosBundleId: 'com.example.attendplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO-izy5yqaBgGtDy79_g6pJLZyIBVWUpI',
    appId: '1:606904438190:ios:7867790ca253ac2a138c3f',
    messagingSenderId: '606904438190',
    projectId: 'attendplus-b771d',
    storageBucket: 'attendplus-b771d.firebasestorage.app',
    iosBundleId: 'com.example.attendplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVWZykSDzxOraakKBS91_Qo0md2QB1quU',
    appId: '1:606904438190:web:730c8508d4860c8d138c3f',
    messagingSenderId: '606904438190',
    projectId: 'attendplus-b771d',
    authDomain: 'attendplus-b771d.firebaseapp.com',
    storageBucket: 'attendplus-b771d.firebasestorage.app',
  );

}